### ISSUE TITLE
Cannot open INI file in Windows folder

### ISSUE THREAD

**Issue by Zolix88** [skaako/raildriver#3]
Hey, I hope you're still active!

I wanted to try out this script with my 2560 Mega, but unfortunately I cannot open the Programfile in C:/Windows. It tries to make a sketch file, but I get this error message: "Error: EPERM: operation not permitted, mkdir 'c:\Windows\Write_Test_1.1'"

When I go and make my own file it opens, but the game doesn't react to my potentiometer inputs.
I do have everything set to default in the testfile you provided, so maybe the problem is that I didn't set something I should have.
(I'm not a programmer so its kinda hard for me to figure out what I should change)

Thanks!

**Comment by Zolix88** [comment]
Update: I realised that INI and INO files are different and I've copied the INI file to the windows folder now, but it still isn't working.

**Comment by Alpakat** [comment]
Just to clarify, you uploaded the code (ino File) to your 2560 Mega and put the ini file in the C:/Windows folder. You now have to change com port in the ini file to the port of your Arduino (shown in the IDE). For me this works.

**Comment by Zolix88** [comment]
Yep, I did all that. Copied the ini file into the windows folder, changet the port to COM5, uploaded your default ino file to my 2560 mega (I even tried someone else's modified version, that didn't work eighter) and I even made sure that my game was on the same drive as the ini file.

I'm using 10k ohm potentiometers and windows 10 64 bit operating system.

**Comment by skaako** [comment]
Hi, did you have any luck getting it to work? To check the Arduino and comms side are working, just open a serial monitor for that port and make sure the data is coming through. If that's good then it's something else.

**Comment by Zolix88** [comment]
Hey, thanks for responding! I managed to get it to work by asking others for help, and somehow, a much simpler code was able to do the same effect for me. I'll paste the code if you're interested. 

```
//int analogPin0 = A0; // potentiometer wiper (middle terminal) connected to analog pin
int analogPin1 = A1; 
int analogPin2 = A2;  // Uncomment as needed. I was testing only a few channels at a time 
int analogPin3 = A3; 
int analogPin4 = A4; 
int analogPin5 = A5;

//int cycle = 0; 
//int dir = 1;
int delayTime = 5;


int val[13] = {0}; // variable to store the value read

void setup() 
{   
    //Initialize serial and wait for port to open: 
    Serial.begin(115200); 
    //while (!Serial){};    //not needed for a Mega
    
}//setup

void loop() 
{
    val[0] = analogRead(analogPin1);     
    val[0] = map(val[0], 0, 1023, 0, 255);
    //
    val[1] = analogRead(analogPin2);     
    val[1] = map(val[1], 0, 1023, 0, 255);
    //
    val[2] = analogRead(analogPin3);     
    val[2] = map(val[2], 0, 1023, 0, 255);
    //
    val[3] = analogRead(analogPin4);     
    val[3] = map(val[3], 0, 1023, 0, 255);
    //
    val[4] = analogRead(analogPin5);     
    val[4] = map(val[4], 0, 1023, 0, 255);
        
    // Start of string output     
    Serial.print("Output: ");
    
    // Padding for numbers 
    for(int i = 0; i < 13; i++)   
    { 
        if(val[i] < 10)     
            Serial.print("  ");     
        else if(val[i] < 100)     
            Serial.print(" ");     

        Serial.print(val[i]); 
        Serial.print(" ");   
        
    }//for

    Serial.println("");

    delay(delayTime);
    
}//loop
```
Its not my code, a kind reddit user helped me out.

**Comment by skaako** [comment]
Not a problem, apologies for not replying sooner. Thanks for posting that code and glad to hear it's working now. Always good to see different implementations and good it is useful. Cheers
